In [56]:
import pandas as pd

In [60]:
df = pd.read_csv("F:\机场噪音\CI_Trend_Summary\Trend_Detail_L2_oneday.csv")

In [61]:
df

,gaul0_name,gaul1_name,gaul2_name,gaul1_code,gaul2_code,202110,202210,202310,Trend_Class,Total_Change
0,Afghanistan,Kabul,Deh Sabz,2411.0,123871.0,NaN,0.042983,0.010648,Data Deficient,NaN
1,Afghanistan,Kabul,Kabul,2411.0,123875.0,NaN,-0.230228,-0.260861,Data Deficient,NaN
2,Akrotiri,Administrative Unit Not Available,Administrative Unit Not Available,3290.0,133967.0,0.040061,-0.000154,-0.102482,Incessant Decrease,-0.142543
3,Albania,Berat,Bashkia Berat,3291.0,133968.0,NaN,-0.000440,NaN,Data Deficient,NaN
4,Albania,Berat,Bashkia Kucove,3291.0,133969.0,NaN,-0.004848,0.006531,Data Deficient,NaN
...,...,...,...,...,...,...,...,...,...,...
20565,Zimbabwe,Mashonaland East,Seke,1725.0,106671.0,0.097619,0.179715,0.249842,Incessant Increase,0.152223
20566,Zimbabwe,Mashonaland West,Chegutu,1726.0,106673.0,-0.196025,-0.256313,-0.357794,Incessant Decrease,-0.161769
20567,Zimbabwe,Mashonaland West,Zvimba,1726.0,106679.0,0.223408,0.355190,0.362366,Incessant Increase,0.138958
20568,Zimbabwe,Matebeleland North,Umguza,1728.0,106693.0,0.019904,0.029785,0.042916,Incessant Increase,0.023011
20569,Åland Islands,Administrative Unit Not Available,Administrative Unit Not Available,3977.0,142778.0,0.392520,0.133609,0.266867,Decrease then Increase,-0.125653

In [66]:
df[(df['202110']>0)&(df['gaul0_name']=='China')]

,gaul0_name,gaul1_name,gaul2_name,gaul1_code,gaul2_code,202110,202210,202310,Trend_Class,Total_Change
4795,China,Anhui Province,Anqing,2531.0,124748.0,0.052455,0.015961,-0.121490,Incessant Decrease,-0.173945
4797,China,Anhui Province,Bozhou,2531.0,124750.0,0.008189,NaN,NaN,Data Deficient,NaN
4798,China,Anhui Province,Chizhou,2531.0,124751.0,0.001157,NaN,-0.006771,Data Deficient,-0.007928
4800,China,Anhui Province,Fuyang,2531.0,124753.0,0.166226,-0.005962,-0.029553,Incessant Decrease,-0.195779
4801,China,Anhui Province,Hefei,2531.0,124754.0,0.006562,-0.074391,-0.050112,Decrease then Increase,-0.056674
...,...,...,...,...,...,...,...,...,...,...
5046,China,Yunnan Province,Chuxiong Yi Autonomous Prefecture,2560.0,125080.0,0.083572,-0.000941,-0.127494,Incessant Decrease,-0.211066
5053,China,Yunnan Province,Yuxi,2560.0,125093.0,0.101398,-0.134255,0.105674,Decrease then Increase,0.004276
5057,China,Zhejiang Province,Jiaxing,2561.0,125097.0,0.343368,0.447850,0.289509,Increase then Decrease,-0.053859
5064,China,Zhejiang Province,Wenzhou,2561.0,125104.0,0.007192,-0.260237,0.009442,Decrease then Increase,0.002250
5065,China,Zhejiang Province,Zhoushan,2561.0,125105.0,0.023876,-0.076558,-0.256061,Incessant Decrease,-0.279938

In [64]:
df[~df['202110'].isna()]

,gaul0_name,gaul1_name,gaul2_name,gaul1_code,gaul2_code,202110,202210,202310,Trend_Class,Total_Change
2,Akrotiri,Administrative Unit Not Available,Administrative Unit Not Available,3290.0,133967.0,0.040061,-0.000154,-0.102482,Incessant Decrease,-0.142543
5,Albania,Diber,Bashkia Bulqize,3292.0,133973.0,-0.000180,NaN,NaN,Data Deficient,NaN
7,Albania,Diber,Bashkia Klos,3292.0,133975.0,0.262911,0.108636,0.192406,Decrease then Increase,-0.070505
8,Albania,Diber,Bashkia Mat,3292.0,133976.0,0.053731,-0.014888,-0.315254,Incessant Decrease,-0.368985
9,Albania,Durres,Bashkia Durres,3293.0,133977.0,0.086755,0.023991,0.056063,Decrease then Increase,-0.030692
...,...,...,...,...,...,...,...,...,...,...
20565,Zimbabwe,Mashonaland East,Seke,1725.0,106671.0,0.097619,0.179715,0.249842,Incessant Increase,0.152223
20566,Zimbabwe,Mashonaland West,Chegutu,1726.0,106673.0,-0.196025,-0.256313,-0.357794,Incessant Decrease,-0.161769
20567,Zimbabwe,Mashonaland West,Zvimba,1726.0,106679.0,0.223408,0.355190,0.362366,Incessant Increase,0.138958
20568,Zimbabwe,Matebeleland North,Umguza,1728.0,106693.0,0.019904,0.029785,0.042916,Incessant Increase,0.023011
20569,Åland Islands,Administrative Unit Not Available,Administrative Unit Not Available,3977.0,142778.0,0.392520,0.133609,0.266867,Decrease then Increase,-0.125653

In [67]:
df['gaul1_code'] = df['gaul1_code'].astype(int)

In [69]:
df.to_csv("test.csv", index=False)